apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "app.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env.variables }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
