apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  maxUnavailable: 0
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels: {{ include "app.selectorLabels" . | nindent 6 }}
