replicaCount: 1

image:
  app:
    repository: "050617084006.dkr.ecr.us-west-1.amazonaws.com/development/swagger"
    tag: "c33b2fb-20251227115813"
    pullPolicy: "Always"

imagePullSecret:

ingress:
  controller: "alb"
  certificationArn: ""
  host:

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpu:
    target: 95
  memory:
    target: 95

resources:
  requests:
    cpu: "20m"
    memory: "20Mi"
    ephemeral-storage: "25Mi"
  limits:
    cpu: "25m"
    memory: "25Mi"
    ephemeral-storage: "30Mi"

env:
  variables:
    VITE_CORE_URL: "https://api.tupic.com/swagger/api.json"
    VITE_OAUTH_URL: "https://api.tupic.com/swagger/oauth.json"
    VITE_BLOG_URL: "/configs/blog-v1-development.json"

