replicaCount: 1

image:
  app:
    repository: "358438442054.dkr.ecr.us-east-1.amazonaws.com/production/swagger"
    tag: "32e7db3"
    pullPolicy: "Always"

imagePullSecret:

ingress:
  controller: "alb"
  certificationArn: ""
  host:

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpu:
    target: 95
  memory:
    target: 95

resources:
  requests:
    cpu: "20m"
    memory: "20Mi"
    ephemeral-storage: "25Mi"
  limits:
    cpu: "25m"
    memory: "25Mi"
    ephemeral-storage: "30Mi"

env:
  variables:

