replicaCount: 1

image:
  app:
    repository: "992382452361.dkr.ecr.eu-central-1.amazonaws.com/swagger/app"
    tag: "5e9fde7-20251227115534"
    pullPolicy: "Always"

imagePullSecret:

ingress:
  controller: "alb"
  certificationArn: ""
  host:

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpu:
    target: 95
  memory:
    target: 95

resources:
  requests:
    cpu: "20m"
    memory: "20Mi"
    ephemeral-storage: "25Mi"
  limits:
    cpu: "25m"
    memory: "25Mi"
    ephemeral-storage: "30Mi"

env:
  variables:
    VITE_CORE_URL: "https://api.gibical.app/swagger/api.json"
    VITE_OAUTH_URL: "https://api.gibical.app/swagger/oauth.json"
    VITE_BLOG_URL: "/configs/blog-v1-development.json"

