replicaCount: 1

image:
  app:
    repository: "992382452361.dkr.ecr.eu-west-1.amazonaws.com/swagger/production"
    tag: "cfacca1-20251112142020"
    pullPolicy: "Always"

imagePullSecret:

ingress:
  controller: "alb"
  certificationArn: "arn:aws:acm:eu-west-1:992382452361:certificate/9a499a45-2e17-44ff-9fd0-76d5ade2da79"
  host:

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpu:
    target: 95
  memory:
    target: 95

resources:
  requests:
    cpu: "20m"
    memory: "20Mi"
    ephemeral-storage: "25Mi"
  limits:
    cpu: "25m"
    memory: "25Mi"
    ephemeral-storage: "30Mi"

env:
  variables:
    VITE_CORE_URL: "https://api.gibical.com/docs/api.json"
    VITE_OAUTH_URL: "https://api.gibical.com/swagger/oauth.json"
    VITE_BLOG_URL: "/configs/blog-v1-production.json"

