name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Build the project
      - name: Build the project
        env:
          VITE_API_URL: https://api.gibical.app/docs/api.json
        run: yarn build

      # Step 5: Upload dist directory to the server using scp
      - name: Deploy Build Artifacts
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./dist/
          target: /srv/swagger/
