name: Build & Deploy App

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - helm-charts/app/**
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: read

concurrency:
  group: build-deploy-app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ github.ref_name == 'main' && 'production' || 'development' }}
    uses: tupicapp/platform-workflows/.github/workflows/shared-eks-build.yaml@main
    permissions:
      contents: read
      id-token: write
      packages: read
    secrets: inherit
    with:
      dockerfile: Dockerfile
      environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
      runner_type: ${{ vars.RUNNER_TYPE || 'ubuntu-latest' }}

  update-manifest:
    name: Update Helm Manifest
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update image tag
        run: |
          FILE="${{ github.ref_name == 'main' && 'helm-charts/app/values.yaml' || 'helm-charts/app/values.development.yaml' }}"
          TAG="${{ needs.build.outputs.image_tag }}"

          echo "Updating $FILE with new tag: $TAG"
          sed -i "s|tag:.*|tag: \"$TAG\"|g" "$FILE"

      - name: Commit and push changes
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          AUTHOR_NAME=$(git log -1 --pretty="%an")
          AUTHOR_EMAIL=$(git log -1 --pretty="%ae")

          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"

          git add helm-charts/app/

          if git diff --cached --quiet; then
            echo "No changes in Helm values - skipping commit."
          else
            echo "Committing Helm update..."
            git commit -m "$COMMIT_MSG"
            git push
          fi
