name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Build the project
      - name: Build the project
        run: yarn build

      - name: Listing files in the workspace after build
        run: |
          echo "Listing contents of the workspace:"
          ls -alh ./dist
          echo "list all files in the workspace"
          ls -alh

      # Step 5: Deploy to the server via SSH
      - name: Deploy Build Artifacts
        run: |
          scp -i ${{ secrets.SSH_KEY }} -r ./dist/* root@${{ vars.SERVER_HOST }}:/srv/swagger/dist
