name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Replace with the Node.js version your app uses
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite app
      - name: Build the Vite app
        run: npm run build

      # Step 5: Deploy to the server
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/swagger
            cp -r ./public/configs/ ./dist/configs/
            git reset --hard HEAD^
            git pull
            # Replace the old build with the new one
            rm -rf ./dist
            rm -rf ./dist
            mv ${{ github.workspace }}/dist ./dist
